package runtime

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

// Secrets never travel in argv. A CLI agent's environment (API keys, host
// overrides, per-session EnvVars) is written to a 0600 file inside the
// worktree's .nxd-prompts/ directory and sourced by the session command,
// which deletes it right after. `ps`, tmux's server log and docker's argv
// therefore only ever see the file path.

// PromptFileRel / EnvFileRel are the worktree-relative locations of the
// prompt and env files. They are referenced RELATIVELY from the command so
// the same string works in tmux (-c workdir), docker (-w /workspace) and ssh
// (cd remoteDir) — all of which start in the worktree.
const (
	PromptDirRel  = ".nxd-prompts"
	PromptFileRel = ".nxd-prompts/prompt.txt"
	EnvFileRel    = ".nxd-prompts/env.sh"
)

// envVarNamePattern is the POSIX-portable environment variable name shape.
var envVarNamePattern = regexp.MustCompile(`^[A-Z_][A-Z0-9_]*$`)

// ValidateEnvVarName rejects names that could break out of an `export NAME=`
// statement or that a POSIX shell would not accept.
func ValidateEnvVarName(name string) error {
	if !envVarNamePattern.MatchString(name) {
		return fmt.Errorf("invalid environment variable name %q (must match ^[A-Z_][A-Z0-9_]*$)", name)
	}
	return nil
}

// passthroughEnvKeys are copied from the current process into every CLI
// agent session. ANTHROPIC_API_KEY is intentionally NOT included: Claude Code
// agents authenticate via the user's OAuth session (Max subscription) rather
// than the pay-per-token API. A runtime that genuinely needs it can set it via
// SessionConfig.EnvVars.
var passthroughEnvKeys = []string{"OPENAI_API_KEY", "GOOGLE_API_KEY", "GEMINI_API_KEY", "OLLAMA_HOST"}

// sessionEnv merges the process passthrough keys with cfg.EnvVars (which win)
// and validates every name.
func sessionEnv(extra map[string]string) (map[string]string, error) {
	env := make(map[string]string, len(passthroughEnvKeys)+len(extra))
	for _, key := range passthroughEnvKeys {
		if val := os.Getenv(key); val != "" {
			env[key] = val
		}
	}
	for key, val := range extra {
		if err := ValidateEnvVarName(key); err != nil {
			return nil, err
		}
		env[key] = val
	}
	return env, nil
}

// RenderEnvFile renders env as sorted `export KEY='value'` lines. Values are
// single-quoted via QuoteShellArg, so `$(...)`, backticks and quotes inside a
// value are inert when the file is sourced.
func RenderEnvFile(env map[string]string) (string, error) {
	keys := make([]string, 0, len(env))
	for k := range env {
		if err := ValidateEnvVarName(k); err != nil {
			return "", err
		}
		keys = append(keys, k)
	}
	sort.Strings(keys)
	var b strings.Builder
	b.WriteString("# generated by nxd — sourced once by the agent session, then deleted\n")
	for _, k := range keys {
		fmt.Fprintf(&b, "export %s=%s\n", k, QuoteShellArg(env[k]))
	}
	return b.String(), nil
}

// RenderDockerEnvFile renders env in docker --env-file syntax (KEY=VALUE, one
// per line, no quoting). Values containing newlines cannot be represented and
// are rejected.
func RenderDockerEnvFile(env map[string]string) (string, error) {
	keys := make([]string, 0, len(env))
	for k := range env {
		if err := ValidateEnvVarName(k); err != nil {
			return "", err
		}
		if strings.ContainsAny(env[k], "\n\r") {
			return "", fmt.Errorf("environment variable %s contains a newline", k)
		}
		keys = append(keys, k)
	}
	sort.Strings(keys)
	var b strings.Builder
	for _, k := range keys {
		fmt.Fprintf(&b, "%s=%s\n", k, env[k])
	}
	return b.String(), nil
}

// envSourcePrefix is prepended to the session command: source the env file
// from the worktree, delete it, and clear CLAUDECODE so a nested Claude Code
// session does not refuse to start.
func envSourcePrefix(hasEnvFile bool) string {
	if !hasEnvFile {
		return "unset CLAUDECODE; "
	}
	return ". ./" + EnvFileRel + " && rm -f ./" + EnvFileRel + "; unset CLAUDECODE; "
}

// writeSecretFile writes content with mode 0600, creating parent dirs.
func writeSecretFile(path, content string) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, []byte(content), 0o600)
}
