// internal/cli/spec.go — `nxd spec` subcommand.
//
// Adopted from ZeeSpec (https://vishalmysore.github.io/zeespec/): an 8-file
// `.spec/` scaffold covering the 5W1H dimensions plus upstream/downstream
// integrations. The planner consumes assembled content as structured
// context, reducing hallucination especially on greenfield setup.
//
// `nxd spec init`     — scaffold .spec/ with templates
// `nxd spec assemble` — concatenate .spec/*.md into AGENTS.md
// `nxd spec validate` — flag unanswered placeholders before dispatch
package cli

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/spf13/cobra"
)

// specDimensionFiles defines the canonical .spec/ scaffold. Order matters —
// it determines the order in the assembled AGENTS.md so the planner reads
// system identity (what/why) before mechanics (how/when).
var specDimensionFiles = []specFile{
	{Name: "what.md", Title: "WHAT — What the system is", Body: specWhatTemplate},
	{Name: "why.md", Title: "WHY — Why the system exists / business rules", Body: specWhyTemplate},
	{Name: "who.md", Title: "WHO — Who can act / roles & permissions", Body: specWhoTemplate},
	{Name: "how.md", Title: "HOW — Architecture & technology choices", Body: specHowTemplate},
	{Name: "when.md", Title: "WHEN — Timing, automation triggers", Body: specWhenTemplate},
	{Name: "where.md", Title: "WHERE — Access points & boundaries", Body: specWhereTemplate},
	{Name: "upstream.md", Title: "UPSTREAM — External system inputs", Body: specUpstreamTemplate},
	{Name: "downstream.md", Title: "DOWNSTREAM — External system outputs", Body: specDownstreamTemplate},
}

type specFile struct {
	Name  string
	Title string
	Body  string
}

func newSpecCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "spec",
		Short: "Manage structured spec for the target project",
		Long: `Spec-driven development scaffolding inspired by ZeeSpec.

` + "`nxd spec init`" + ` creates a .spec/ folder with 8 markdown files covering
the 5W1H dimensions of your system. Fill them in before running ` + "`nxd req`" + `;
the planner will pick them up as structured context, reducing hallucination
on greenfield setups.`,
	}
	cmd.AddCommand(newSpecInitCmd())
	cmd.AddCommand(newSpecAssembleCmd())
	cmd.AddCommand(newSpecValidateCmd())
	return cmd
}

func newSpecInitCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "init [target-dir]",
		Short: "Scaffold .spec/ with the 8 dimension templates",
		Args:  cobra.MaximumNArgs(1),
		RunE:  runSpecInit,
	}
	cmd.Flags().Bool("force", false, "Overwrite existing files")
	return cmd
}

func newSpecAssembleCmd() *cobra.Command {
	return &cobra.Command{
		Use:   "assemble [target-dir]",
		Short: "Concatenate .spec/*.md into AGENTS.md (master prompt)",
		Args:  cobra.MaximumNArgs(1),
		RunE:  runSpecAssemble,
	}
}

func newSpecValidateCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "validate [target-dir]",
		Short: "Flag unanswered placeholders in .spec/ files",
		Args:  cobra.MaximumNArgs(1),
		RunE:  runSpecValidate,
	}
	cmd.SilenceUsage = true
	cmd.SilenceErrors = true
	return cmd
}

func resolveSpecDir(args []string) (string, string) {
	target := "."
	if len(args) > 0 {
		target = args[0]
	}
	abs, err := filepath.Abs(target)
	if err != nil {
		abs = target
	}
	return abs, filepath.Join(abs, ".spec")
}

func runSpecInit(cmd *cobra.Command, args []string) error {
	_, specDir := resolveSpecDir(args)
	force, _ := cmd.Flags().GetBool("force")
	out := cmd.OutOrStdout()

	if err := os.MkdirAll(specDir, 0o755); err != nil {
		return fmt.Errorf("create %s: %w", specDir, err)
	}

	created := 0
	skipped := 0
	for _, f := range specDimensionFiles {
		path := filepath.Join(specDir, f.Name)
		if !force {
			if _, err := os.Stat(path); err == nil {
				fmt.Fprintf(out, "  skipped: %s (use --force to overwrite)\n", f.Name)
				skipped++
				continue
			}
		}
		content := fmt.Sprintf("# %s\n\n%s\n", f.Title, f.Body)
		if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
			return fmt.Errorf("write %s: %w", path, err)
		}
		fmt.Fprintf(out, "  created: %s\n", f.Name)
		created++
	}

	fmt.Fprintf(out, "\nscaffold complete in %s — %d created, %d skipped\n", specDir, created, skipped)
	fmt.Fprintf(out, "next: edit each file, then run `nxd spec assemble` and `nxd req`.\n")
	return nil
}

func runSpecAssemble(cmd *cobra.Command, args []string) error {
	target, specDir := resolveSpecDir(args)
	out := cmd.OutOrStdout()

	if _, err := os.Stat(specDir); err != nil {
		return fmt.Errorf("no .spec/ at %s — run `nxd spec init` first", target)
	}

	var b strings.Builder
	b.WriteString("# AGENTS.md — assembled spec\n\n")
	b.WriteString("Generated by `nxd spec assemble`. Hand to the planner via `nxd req --file AGENTS.md`.\n\n")

	for _, f := range specDimensionFiles {
		path := filepath.Join(specDir, f.Name)
		data, err := os.ReadFile(path)
		if err != nil {
			fmt.Fprintf(out, "  warning: missing %s — run `nxd spec init`\n", f.Name)
			continue
		}
		b.WriteString("---\n\n")
		b.Write(data)
		if !strings.HasSuffix(string(data), "\n") {
			b.WriteString("\n")
		}
		b.WriteString("\n")
	}

	outPath := filepath.Join(target, "AGENTS.md")
	if err := os.WriteFile(outPath, []byte(b.String()), 0o644); err != nil {
		return fmt.Errorf("write %s: %w", outPath, err)
	}
	fmt.Fprintf(out, "wrote %s (%d bytes)\n", outPath, b.Len())
	return nil
}

// placeholderTokens are tokens that indicate a spec file has unanswered
// content. Found in templates (TODO / FILL_IN) or in user-edited files.
var placeholderTokens = []string{"TODO", "FILL_IN", "???", "[ ]", "<placeholder>"}

func runSpecValidate(cmd *cobra.Command, args []string) error {
	_, specDir := resolveSpecDir(args)
	out := cmd.OutOrStdout()

	type finding struct {
		File  string
		Line  int
		Token string
	}
	var findings []finding
	missingFiles := 0

	for _, f := range specDimensionFiles {
		path := filepath.Join(specDir, f.Name)
		data, err := os.ReadFile(path)
		if err != nil {
			missingFiles++
			fmt.Fprintf(out, "  missing: %s\n", f.Name)
			continue
		}
		lines := strings.Split(string(data), "\n")
		for i, line := range lines {
			for _, tok := range placeholderTokens {
				if strings.Contains(line, tok) {
					findings = append(findings, finding{File: f.Name, Line: i + 1, Token: tok})
				}
			}
		}
	}

	sort.Slice(findings, func(i, j int) bool {
		if findings[i].File != findings[j].File {
			return findings[i].File < findings[j].File
		}
		return findings[i].Line < findings[j].Line
	})

	for _, f := range findings {
		fmt.Fprintf(out, "  %s:%d unresolved %s\n", f.File, f.Line, f.Token)
	}

	if missingFiles > 0 || len(findings) > 0 {
		fmt.Fprintf(out, "\n%d unresolved placeholder(s), %d missing file(s).\n", len(findings), missingFiles)
		fmt.Fprintf(out, "Fill them in before running `nxd req` for best planner results.\n")
		return fmt.Errorf("spec incomplete: %d placeholders, %d missing files", len(findings), missingFiles)
	}

	fmt.Fprintf(out, "spec complete — all %d dimension files present, no placeholders.\n", len(specDimensionFiles))
	return nil
}

// LoadSpecForRequirement returns the assembled .spec/ content for the given
// repo, or empty string if no .spec/ exists. Called by the planner to
// augment requirements with structured spec context.
//
// The planner is expected to prepend this to the user's requirement text.
func LoadSpecForRequirement(repoPath string) string {
	specDir := filepath.Join(repoPath, ".spec")
	if _, err := os.Stat(specDir); err != nil {
		return ""
	}
	var b strings.Builder
	b.WriteString("# Project specification (from .spec/)\n\n")
	wroteAny := false
	for _, f := range specDimensionFiles {
		data, err := os.ReadFile(filepath.Join(specDir, f.Name))
		if err != nil {
			continue
		}
		if strings.TrimSpace(string(data)) == "" {
			continue
		}
		b.WriteString("## ")
		b.WriteString(f.Title)
		b.WriteString("\n\n")
		b.Write(data)
		if !strings.HasSuffix(string(data), "\n") {
			b.WriteString("\n")
		}
		b.WriteString("\n")
		wroteAny = true
	}
	if !wroteAny {
		return ""
	}
	return b.String()
}
