package config

import (
	"fmt"
	"os"

	"gopkg.in/yaml.v3"
)

// gemma4Default returns a ModelConfig preset for the Gemma 4 26B model
// using the google+ollama dual provider with the given token limit.
func gemma4Default(maxTokens int) ModelConfig {
	return ModelConfig{
		Provider:          "google+ollama",
		Model:             "gemma4:26b",
		GoogleModel:       "gemma-4-26b-a4b-it",
		MaxTokens:         maxTokens,
		FallbackCooldownS: 60,
	}
}

// DefaultConfig returns a Config populated with sensible defaults.
// The returned value passes Validate() without modification.
func DefaultConfig() Config {
	return Config{
		Version: "1.0",
		Workspace: WorkspaceConfig{
			StateDir:            "~/.nxd",
			Backend:             "sqlite",
			LogLevel:            "info",
			LogRetentionDays:    30,
			UpdateCheck:         true,
			UpdateIntervalHours: 48,
		},
		Models: ModelsConfig{
			TechLead:     gemma4Default(16000),
			Senior:       gemma4Default(8000),
			Intermediate: gemma4Default(4000),
			Junior:       gemma4Default(4000),
			QA:           gemma4Default(8000),
			Supervisor:   gemma4Default(4000),
			Manager:      gemma4Default(8000),
			Investigator: gemma4Default(16000),
		},
		Routing: RoutingConfig{
			JuniorMaxComplexity:           3,
			IntermediateMaxComplexity:     5,
			MaxRetriesBeforeEscalation:    2,
			MaxQAFailuresBeforeEscalation: 3,
			MaxSeniorRetries:              2,
			MaxManagerAttempts:            2,
		},
		Monitor: MonitorConfig{
			PollIntervalMs:         10000,
			StuckThresholdS:        120,
			ContextFreshnessTokens: 150000,
		},
		Cleanup: CleanupConfig{
			WorktreePrune:       "immediate",
			BranchRetentionDays: 7,
			LogArchive:          "file",
		},
		Merge: MergeConfig{
			AutoMerge:  true,
			BaseBranch: "main",
			Mode:       "local",
			PRTemplate: "## Story: {story_id}\n{description}\n### Acceptance Criteria\n{acceptance_criteria}\n",
		},
		Planning: PlanningConfig{
			SequentialFilePatterns: []string{"package.json", "*.config.*", "src/core/*"},
			MaxStoryComplexity:     5,
		},
		Runtimes: map[string]RuntimeConfig{
			"aider": {
				Command: "aider",
				Args:    []string{"--model", "ollama_chat/deepseek-coder-v2:latest", "--no-auto-commits"},
				Models:  []string{"deepseek-coder-v2", "qwen2.5-coder"},
				Detection: RuntimeDetection{
					IdlePattern:       "^>",
					PermissionPattern: `\[Y/n\]`,
				},
			},
			"claude-code": {
				Command: "claude",
				Args:    []string{"--dangerously-skip-permissions"},
				Models:  []string{"opus-4", "sonnet-4", "haiku-4"},
				Detection: RuntimeDetection{
					IdlePattern:       `^\$\s*$`,
					PermissionPattern: `\[Y/n\]`,
					PlanModePattern:   "Plan mode",
				},
			},
			"codex": {
				Command: "codex",
				Args:    []string{"--full-auto"},
				Models:  []string{"o3", "o4-mini"},
				Detection: RuntimeDetection{
					IdlePattern:       "Codex>",
					PermissionPattern: "approve|deny",
				},
			},
			"gemma": {
				Native:           true,
				MaxIterations:    20,
				Models:           []string{"gemma4"},
				CommandAllowlist: []string{"go build ./...", "go test ./...", "npm test", "npm run build", "make", "make test"},
			},
		},
	}
}

// DefaultYAML marshals DefaultConfig to YAML bytes suitable for writing
// as an nxd.yaml configuration file.
func DefaultYAML() ([]byte, error) {
	cfg := DefaultConfig()
	data, err := yaml.Marshal(cfg)
	if err != nil {
		return nil, fmt.Errorf("marshalling default config: %w", err)
	}

	header := []byte("# NXD configuration — generated by 'nxd init'\n" +
		"# See https://github.com/tzone85/nexus-dispatch for documentation.\n\n")
	return append(header, data...), nil
}

// LoadFromFile reads a YAML configuration file, overlays it on top of
// DefaultConfig (so unset fields keep their defaults), validates, and
// returns the result.
func LoadFromFile(path string) (Config, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return Config{}, fmt.Errorf("reading config file: %w", err)
	}

	cfg := DefaultConfig()

	if err := yaml.Unmarshal(data, &cfg); err != nil {
		return Config{}, fmt.Errorf("parsing config YAML: %w", err)
	}

	if err := cfg.Validate(); err != nil {
		return Config{}, fmt.Errorf("config validation: %w", err)
	}

	return cfg, nil
}
