package config

import (
	"fmt"
	"os"

	"gopkg.in/yaml.v3"
)

// DefaultConfig returns a Config populated with sensible defaults.
// The returned value passes Validate() without modification.
func DefaultConfig() Config {
	return Config{
		Version: "1.0",
		Workspace: WorkspaceConfig{
			StateDir:         "~/.nxd",
			Backend:          "sqlite",
			LogLevel:         "info",
			LogRetentionDays: 30,
		},
		Models: ModelsConfig{
			TechLead:     ModelConfig{Provider: "ollama", Model: "deepseek-coder-v2:latest", MaxTokens: 16000},
			Senior:       ModelConfig{Provider: "ollama", Model: "qwen2.5-coder:32b", MaxTokens: 8000},
			Intermediate: ModelConfig{Provider: "ollama", Model: "qwen2.5-coder:14b", MaxTokens: 4000},
			Junior:       ModelConfig{Provider: "ollama", Model: "qwen2.5-coder:7b", MaxTokens: 4000},
			QA:           ModelConfig{Provider: "ollama", Model: "qwen2.5-coder:14b", MaxTokens: 8000},
			Supervisor:   ModelConfig{Provider: "ollama", Model: "deepseek-coder-v2:latest", MaxTokens: 4000},
		},
		Routing: RoutingConfig{
			JuniorMaxComplexity:           3,
			IntermediateMaxComplexity:     5,
			MaxRetriesBeforeEscalation:    2,
			MaxQAFailuresBeforeEscalation: 3,
		},
		Monitor: MonitorConfig{
			PollIntervalMs:         10000,
			StuckThresholdS:        120,
			ContextFreshnessTokens: 150000,
		},
		Cleanup: CleanupConfig{
			WorktreePrune:       "immediate",
			BranchRetentionDays: 7,
			LogArchive:          "file",
		},
		Merge: MergeConfig{
			AutoMerge:  true,
			BaseBranch: "main",
			Mode:       "local",
			PRTemplate: "## Story: {story_id}\n{description}\n### Acceptance Criteria\n{acceptance_criteria}\n",
		},
		Planning: PlanningConfig{
			SequentialFilePatterns: []string{"package.json", "*.config.*", "src/core/*"},
			MaxStoryComplexity:     5,
		},
		Runtimes: map[string]RuntimeConfig{
			"aider": {
				Command: "aider",
				Args:    []string{"--model", "ollama_chat/deepseek-coder-v2:latest", "--no-auto-commits"},
				Models:  []string{"deepseek-coder-v2", "qwen2.5-coder"},
				Detection: RuntimeDetection{
					IdlePattern:       "^>",
					PermissionPattern: `\[Y/n\]`,
				},
			},
			"claude-code": {
				Command: "claude",
				Args:    []string{"--dangerously-skip-permissions"},
				Models:  []string{"opus-4", "sonnet-4", "haiku-4"},
				Detection: RuntimeDetection{
					IdlePattern:       `^\$\s*$`,
					PermissionPattern: `\[Y/n\]`,
					PlanModePattern:   "Plan mode",
				},
			},
			"codex": {
				Command: "codex",
				Args:    []string{"--full-auto"},
				Models:  []string{"o3", "o4-mini"},
				Detection: RuntimeDetection{
					IdlePattern:       "Codex>",
					PermissionPattern: "approve|deny",
				},
			},
		},
	}
}

// DefaultYAML marshals DefaultConfig to YAML bytes suitable for writing
// as an nxd.yaml configuration file.
func DefaultYAML() ([]byte, error) {
	cfg := DefaultConfig()
	data, err := yaml.Marshal(cfg)
	if err != nil {
		return nil, fmt.Errorf("marshalling default config: %w", err)
	}

	header := []byte("# NXD configuration — generated by 'nxd init'\n" +
		"# See https://github.com/tzone85/nexus-dispatch for documentation.\n\n")
	return append(header, data...), nil
}

// LoadFromFile reads a YAML configuration file, overlays it on top of
// DefaultConfig (so unset fields keep their defaults), validates, and
// returns the result.
func LoadFromFile(path string) (Config, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return Config{}, fmt.Errorf("reading config file: %w", err)
	}

	cfg := DefaultConfig()

	if err := yaml.Unmarshal(data, &cfg); err != nil {
		return Config{}, fmt.Errorf("parsing config YAML: %w", err)
	}

	if err := cfg.Validate(); err != nil {
		return Config{}, fmt.Errorf("config validation: %w", err)
	}

	return cfg, nil
}
